version: '3.7'

services:
  clamav:
    #debian: image: mkodockx/docker-clamav
    image: mkodockx/docker-clamav:buster
    container_name: nextav
    restart: unless-stopped
    volumes:
      - clam:/var/lib/clamav
    healthcheck:
      test: ["CMD", "./check.sh"]
      interval: 60s
      retries: 3
      start_period: 120s